const fs = require('fs')
const path = require('path')
const a = fs.readFileSync(path.join(__dirname,"exJSON.json"))
const b = JSON.parse(a)
console.log(b[1]["age"])

const q = fs.readFileSync(path.join(__dirname,"ex2JSON.json"))
const w = JSON.parse(q)
console.log(w)
console.log(w.지브리OST리스트)
console.log(w.지브리OST리스트[0])
console.log(w.지브리OST리스트[0].name)
console.log(w.지브리OST리스트[0].song)